Siciarek\PhotoGalleryBundle\Entity\Album:
    type: entity
    repositoryClass: Siciarek\PhotoGalleryBundle\Entity\AlbumRepository
    table: photogallery_album
#    gedmo:
#        translation:
#            locale: locale
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        sequence_number:
            type: integer
            nullable: false
        title:
            type: string
            length: 255
            nullable: true
#            gedmo: [ translatable ]
        slug:
          type: string
          length: 255
          gedmo:
            slug:
              fields:
                - title
        description:
            type: text
            length: 10000
            nullable: true
#            gedmo: [ translatable ]
        is_visible:
            type: boolean
            nullable: false
        expires_at:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        cover:
            targetEntity: Image
            mappedBy: albumcov
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: album
