Siciarek\PhotoGalleryBundle\Entity\Creator:
    type: entity
    table: photogallery_creator
    repositoryClass: Siciarek\PhotoGalleryBundle\Entity\CreatorRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 255
            nullable: false
        email:
            type: string
            length: 255
            nullable: false
        first_name:
            type: string
            length: 255
            nullable: true
        last_name:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            nullable: true
        created_at:
            type: datetime
            gedmo:
              timestampable:
                  on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        albums:
            targetEntity: Album
            mappedBy: creator
