Siciarek\PhotoGalleryBundle\Entity\Image:
    type: entity
    repositoryClass: Siciarek\PhotoGalleryBundle\Entity\ImageRepository
    table: photogallery_image
    gedmo:
        translation:
            locale: locale
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        sequence_number:
            type: integer
            nullable: false
        title:
            type: string
            length: 255
            nullable: true
            gedmo: [ translatable ]
        description:
            type: text
            length: 10000
            nullable: true
            gedmo: [ translatable ]
        path:
            type: text
            length: 10000
            nullable: false
        mime_type:
            type: string
            length: 255
            nullable: false
        file_size:
            type: integer
            nullable: false
        width:
            type: integer
            nullable: false
        height:
            type: integer
            nullable: false
        is_visible:
            type: boolean
            nullable: false
        expires_at:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        album:
            targetEntity: Album
            inversedBy: images
    oneToOne:
        thumbnail:
            targetEntity: Image
