<?php

namespace Siciarek\PhotoGalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorRepository extends EntityRepository
{
}
